# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/twm/t1/extract-files.sh - DO NOT EDIT

# All the blobs necessary for t1
PRODUCT_COPY_FILES += \
    vendor/twm/t1/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/twm/t1/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/twm/t1/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/twm/t1/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/twm/t1/proprietary/libgsl.so:system/lib//libgsl.so \
    vendor/twm/t1/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/twm/t1/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/twm/t1/proprietary/qmuxd:system/bin/qmuxd \
    vendor/twm/t1/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/twm/t1/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/twm/t1/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/twm/t1/proprietary/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/twm/t1/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/twm/t1/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/twm/t1/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/twm/t1/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/twm/t1/proprietary/libdll.so:system/lib/libdll.so \
    vendor/twm/t1/proprietary/libcm.so:system/lib/libcm.so \
    vendor/twm/t1/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/twm/t1/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/twm/t1/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/twm/t1/proprietary/libwms.so:system/lib/libwms.so \
    vendor/twm/t1/proprietary/libnv.so:system/lib/libnv.so \
    vendor/twm/t1/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/twm/t1/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/twm/t1/proprietary/libdss.so:system/lib/libdss.so \
    vendor/twm/t1/proprietary/libauth.so:system/lib/libauth.so \
    vendor/twm/t1/proprietary/lights.msm7k.so:system/lib/hw/lights.msm7k.so \
    vendor/twm/t1/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/twm/t1/proprietary/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/twm/t1/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/twm/t1/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/twm/t1/proprietary/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/twm/t1/proprietary/libOmxAacDec.so:/system/lib/libOmxAacDec.so \
    vendor/twm/t1/proprietary/libOmxWmvDec.so:/system/lib/libOmxWmvDec.so \
    vendor/twm/t1/proprietary/libOmxQcelpDec.so:/system/lib/libOmxQcelpDec.so \
    vendor/twm/t1/proprietary/libOmxAmrEnc.so:/system/lib/libOmxAmrEnc.so \
    vendor/twm/t1/proprietary/libOmxEvrcDec.so:/system/lib/libOmxEvrcDec.so \
    vendor/twm/t1/proprietary/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/twm/t1/proprietary/libOmxAmrDec.so:/system/lib/libOmxAmrDec.so \
    vendor/twm/t1/proprietary/libOmxWmaDec.so:/system/lib/libOmxWmaDec.so \
    vendor/twm/t1/proprietary/libOmxMp3Dec.so:/system/lib/libOmxMp3Dec.so \
    vendor/twm/t1/proprietary/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/twm/t1/proprietary/libmm-adspsvc.so:/system/lib/libmm-adspsvc.so \
    vendor/twm/t1/proprietary/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/twm/t1/proprietary/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/twm/t1/proprietary/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/twm/t1/proprietary/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/twm/t1/proprietary/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/twm/t1/proprietary/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/twm/t1/proprietary/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/twm/t1/proprietary/libloc_api.so:system/lib/libloc_api.so \
    vendor/twm/t1/proprietary/libloc_api.so:obj/lib/libloc_api.so \
    vendor/twm/t1/proprietary/libloc_api-rpc.so:system/lib/libloc_api-rpc.so \
    vendor/twm/t1/proprietary/libloc_api-rpc.so:obj/lib/libloc_api-rpc.so \
    vendor/twm/t1/proprietary/libgps.so:obj/lib/libgps.so \
    vendor/twm/t1/proprietary/libgps.so:system/lib/libgps.so \
    vendor/twm/t1/proprietary/libcommondefs.so:obj/lib/libcommondefs.so \
    vendor/twm/t1/proprietary/libcommondefs.so:system/lib/libcommondefs.so 
    
